name: Release

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - uses: actions/setup-node@master
              with:
                  node-version: 12

            - run: npm install
            - run: npm run build:dist

            - uses: codfish/semantic-release-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
